name: <snakemake_template>
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake=9.16.3
  - snakemake-executor-plugin-slurm=2.2.0
  - snakedeploy=0.16.0
  - snakefmt=0.11.4 # snakemake code formatter
  - graphviz=9.0.0 # optional, to visualize the DAG
