# This file is for various variables used throughout the workflow.
# How things are run (executor, resources etc) is set on the command line instead

output_dir: "output"
# input folder is expected to contain a subfolder for each sampleID/barcode
# then all fastq files in each subfolder is concatenated and the folder name is 
# used a sample ID downstream
input_dir: ".test/nanopore_run_xyz123/fastq_pass"
tmp_dir: "tmp"
db_path: ".test/db_sintax.fa"
log_dir: "logs"

# Max number of threads for multithreaded rules
max_threads: 32